#!/usr/bin/env python3
"""
Reads ../.env.local and generates
server-backend/main/xiaozhi-server/data/.config.yaml
so the xiaozhi-esp32-server backend uses OpenRouter as its LLM.

Usage:
    python scripts/apply_openrouter_config.py

Run this every time you change .env.local, then (re)start the server:
    cd server-backend/main/xiaozhi-server
    python app.py
"""
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ENV_FILE = ROOT / ".env.local"
CONFIG_DATA_DIR = ROOT / "server-backend" / "main" / "xiaozhi-server" / "data"
CONFIG_OVERRIDE_FILE = CONFIG_DATA_DIR / ".config.yaml"


def load_env(path: Path) -> dict:
    values = {}
    if not path.exists():
        print(f"ERROR: {path} not found. Copy .env.local.example to .env.local first.")
        sys.exit(1)
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, val = line.partition("=")
        values[key.strip()] = val.strip()
    return values


def main():
    env = load_env(ENV_FILE)

    api_key = env.get("OPENROUTER_API_KEY", "")
    base_url = env.get("OPENROUTER_BASE_URL", "https://openrouter.ai/api/v1")
    model_name = env.get("OPENROUTER_MODEL", "openai/gpt-4o-mini")
    temperature = env.get("OPENROUTER_TEMPERATURE", "0.7")
    max_tokens = env.get("OPENROUTER_MAX_TOKENS", "500")
    lan_ip = env.get("SERVER_LAN_IP", "127.0.0.1")
    ws_port = env.get("SERVER_WS_PORT", "8000")
    http_port = env.get("SERVER_HTTP_PORT", "8003")

    if not api_key or api_key.startswith("sk-or-v1-xxxx"):
        print("ERROR: OPENROUTER_API_KEY is missing/placeholder in .env.local.")
        print("       Edit .env.local and set your real OpenRouter key, then re-run this script.")
        sys.exit(1)

    CONFIG_DATA_DIR.mkdir(parents=True, exist_ok=True)

    yaml_content = f"""\
# AUTO-GENERATED by scripts/apply_openrouter_config.py
# Do not edit by hand — edit ../../../../.env.local instead and re-run the script.

server:
  ip: 0.0.0.0
  port: {ws_port}
  http_port: {http_port}
  websocket: ws://{lan_ip}:{ws_port}/xiaozhi/v1/
  vision_explain: http://{lan_ip}:{http_port}/mcp/vision/explain

selected_module:
  LLM: OpenRouterLLM

LLM:
  OpenRouterLLM:
    type: openai
    base_url: {base_url}
    model_name: {model_name}
    api_key: {api_key}
    temperature: {temperature}
    max_tokens: {max_tokens}
    top_p: 1
    frequency_penalty: 0
"""

    CONFIG_OVERRIDE_FILE.write_text(yaml_content, encoding="utf-8")
    print(f"Wrote {CONFIG_OVERRIDE_FILE}")
    print(f"LLM -> OpenRouter model '{model_name}' via {base_url}")
    print(f"WebSocket for the ESP32 firmware -> ws://{lan_ip}:{ws_port}/xiaozhi/v1/")


if __name__ == "__main__":
    main()
